# Generated by Django 2.2 on 2019-04-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_commnent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnent',
            new_name='Comment',
        ),
    ]
