# Generated by Django 2.2.1 on 2019-05-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190502_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
