# Generated by Django 2.2.1 on 2019-05-09 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190509_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='img',
        ),
    ]
