# Generated by Django 2.2.1 on 2019-05-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
